version: "3.7"
services:
  client:
    environment:
      - NODE_ENV=production
      - PORT=5076
    image: solonsscale/fast-dash:latest
    working_dir: /app
    stdin_open: true
    ports:
      - "5076:5076"
    restart: unless-stopped
    volumes:
      - data:/app

volumes:
  data:
