version: "3.7"
services:
  client:
    environment:
      - NODE_ENV=production
      - PORT=5076
    image: solonsscale/fast-dash-postgres:latest
    working_dir: /app
    stdin_open: true
    ports:
      - "5076:5076"
    restart: unless-stopped
    volumes:
      - data:/app
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=Shortcuts
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  data:
  pg-data:
    driver: local
